[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/ai-chat"
  to = "https://yjw123456.app.n8n.cloud/webhook/ai-chat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200