[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/ai-chat"
  to = "/.netlify/functions/ai-chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200