[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  ai-chat.timeout = 180

[[redirects]]
  from = "/api/ai-chat"
  to = "/.netlify/functions/ai-chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200